"""Core layer: surfaces, colour, geometry, input, scene composition, ECS."""

from .color import (Color, Gradient, PALETTES, fast_color,
                    BLACK, RED, GREEN, BLUE, YELLOW, CYAN, MAGENTA, WHITE,
                    ORANGE, PURPLE, PINK, DIM)
from .geom import Vec2, Vec3, Mat4
from .canvas import Canvas, HiResCanvas, Cell, SHADE_CHARS, LINE_CHARS
from .sprite import Sprite
from .state import (SceneState, scene_state, clear_scene_states,
                    list_scene_states, SceneStateStore)
from .scene import Scene, Layer
from .camera import Camera
from .input import (Input, KeyState, open_input, KeyEvent, MouseEvent,
                    ResizeEvent, HAVE_TERMIOS,
                    KEY_UP, KEY_DOWN, KEY_LEFT, KEY_RIGHT, KEY_ENTER,
                    KEY_SPACE, KEY_ESCAPE, KEY_TAB, KEY_SHIFT_TAB,
                    KEY_BACKSPACE, KEY_DELETE, KEY_INSERT, KEY_HOME,
                    KEY_END, KEY_PAGE_UP, KEY_PAGE_DOWN, KEY_CTRL_C,
                    KEY_CTRL_D, KEY_CTRL_Z)
from .util import (clamp, lerp, ir, ramp, phase, wave, osc, in_bounds,
                   approach, move_toward, bounce, dist, lerp_color,
                   smoothstep, ramp_color, rows_for_width)
from .assets import (Assets, assets, load_sprite, load_palette,
                     load_model, load_text,
                     AssetError, AssetNotFoundError, UnsupportedAssetError,
                     AssetParseError, default_store)
from .ecs import (Component, EcsEntity, World, System, Transform,
                  SpriteComponent, SpriteRenderSystem)
from .term import (detect_color_depth, terminal_size, is_tty, monotonic,
                   supports_altscreen, DEFAULT_TERM_SIZE, CHAR_ASPECT,
                   RawMode, TerminalSession, HAVE_TERMIOS as HAVE_POSIX_TERMIOS,
                   posix_terminal_available, install_resize_handler,
                   remove_resize_handler)

__all__ = [
                    'BLACK',
                    'BLUE',
                    'CHAR_ASPECT',
                    'CYAN',
                    'DEFAULT_TERM_SIZE',
                    'DIM',
                    'GREEN',
                    'HAVE_POSIX_TERMIOS',
                    'HAVE_TERMIOS',
                    'KEY_BACKSPACE',
                    'KEY_CTRL_C',
                    'KEY_CTRL_D',
                    'KEY_CTRL_Z',
                    'KEY_DELETE',
                    'KEY_DOWN',
                    'KEY_END',
                    'KEY_ENTER',
                    'KEY_ESCAPE',
                    'KEY_HOME',
                    'KEY_INSERT',
                    'KEY_LEFT',
                    'KEY_PAGE_DOWN',
                    'KEY_PAGE_UP',
                    'KEY_RIGHT',
                    'KEY_SHIFT_TAB',
                    'KEY_SPACE',
                    'KEY_TAB',
                    'KEY_UP',
                    'LINE_CHARS',
                    'MAGENTA',
                    'ORANGE',
                    'PALETTES',
                    'PINK',
                    'PURPLE',
                    'RED',
                    'SHADE_CHARS',
                    'WHITE',
                    'YELLOW',
                    'AssetError',
                    'AssetNotFoundError',
                    'AssetParseError',
                    'Assets',
                    'Camera',
                    'Canvas',
                    'Cell',
                    'Color',
                    'Component',
                    'EcsEntity',
                    'Gradient',
                    'HiResCanvas',
                    'Input',
                    'KeyEvent',
                    'KeyState',
                    'Layer',
                    'Mat4',
                    'MouseEvent',
                    'RawMode',
                    'ResizeEvent',
                    'Scene',
                    'SceneState',
                    'SceneStateStore',
                    'Sprite',
                    'SpriteComponent',
                    'SpriteRenderSystem',
                    'System',
                    'TerminalSession',
                    'Transform',
                    'UnsupportedAssetError',
                    'Vec2',
                    'Vec3',
                    'World',
                    'approach',
                    'assets',
                    'bounce',
                    'clamp',
                    'clear_scene_states',
                    'default_store',
                    'detect_color_depth',
                    'dist',
                    'in_bounds',
                    'install_resize_handler',
                    'ir',
                    'is_tty',
                    'lerp',
                    'lerp_color',
                    'list_scene_states',
                    'load_model',
                    'load_palette',
                    'load_sprite',
                    'load_text',
                    'monotonic',
                    'move_toward',
                    'open_input',
                    'osc',
                    'phase',
                    'posix_terminal_available',
                    'ramp',
                    'ramp_color',
                    'remove_resize_handler',
                    'rows_for_width',
                    'scene_state',
                    'smoothstep',
                    'supports_altscreen',
                    'terminal_size',
                    'wave',
]
